name: Go
on:
  push:
    tags: '*'
jobs:

  build:
    name: Package and upload to Github release
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make
    
    - name: Upload to release
      uses: TheDoctor0/zip-release@v0.2.0
      with:
        # Filename for archive
#         filename: # default is release.zip
        # Base path for archive files
        path: ouput
        # List of excluded files/directories
#         exclusions: # optional, default is 
